import type { Metadata } from 'next';

import './globals.css';

import React from 'react';

import TopNavigationBar from '@/components/navigation/top-navigation-bar';
import { ThemeProvider } from '@/components/providers/theme-provider';

export const metadata: Metadata = {
  title: {
    default: 'Starter',
    template: '%s | Starter',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`} vaul-drawer-wrapper="">
        <div className="bg-background relative flex min-h-screen flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TopNavigationBar />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
